"
" a moj pliczek vima ;]
"
"
let $PATH = expand("~/.nvm/versions/node/v24.14.0/bin") . ":" . $PATH

set nocompatible    " hmm ? :)
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
let s:cfg_dir = fnamemodify(resolve(expand($MYVIMRC)), ':h')
call vundle#begin()
execute 'source ' . fnameescape(s:cfg_dir . '/plugins.shared.vim')

" kolorki
Plugin 'ghifarit53/tokyonight-vim'                       " colorscheme: tokyonight fork
Plugin 'nordtheme/vim'                                   " colorscheme: nord

" boxy / nawigacja / szukanie
" wyrownywanie / edycja
" syntax
Plugin 'saltstack/salt-vim'                              " SaltStack syntax
"Plugin 'ap/vim-css-color'                               " preview CSS colors inline

" framework / domain
Plugin 'exu/pgsql.vim'                                   " PostgreSQL SQL syntax
Plugin 'vim-ruby/vim-ruby'                               " Ruby syntax and indent
Plugin 'tpope/vim-rails'                                 " Rails helpers

Plugin 'kylef/apiblueprint.vim'                          " API Blueprint syntax

call vundle#end()
execute 'source ' . fnameescape(s:cfg_dir . '/vimrc.shared')

set tabstop=2    " szerokosc tabulacji :)
set shiftwidth=2 " szerokosc automagicznego wciecia
"set smarttab - moze uzyc

set encoding=utf-8

let g:airline_powerline_fonts = 1
