set -g default-terminal "screen-256color"
#set -g default-terminal "tmux-255color"
#set -ag terminal-overrides ",xterm-256color:RGB"

set -s escape-time 50

set -g prefix2 C-a
#bind C-a send-prefix -2

# List of plugins
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'

### configure plugins
set -g @dracula-show-powerline false

set -g @dracula-show-left-icon "#h | #S"

set -g @dracula-plugins "ssh-session spr cpu-usage ram-usage weather time"
set -g @dracula-time-format "%R %F"
set -g @dracula-military-time true

# Spotify
set -g @dracula-spr-play-icon "♫ "
set -g @dracula-spr-pause-icon "● "
set -g @dracula-spr-remote true
set -g @dracula-spr-remote-play-pause "M-/"
set -g @dracula-spr-remote-back "M-,"
set -g @dracula-spr-remote-next "M-."

# Weather
set -g @dracula-show-location true
set -g @dracula-weather-hide-errors false

set -g @dracula-show-fahrenheit false
set -g @dracula-show-ssh-only-when-connected true

set -g @dracula-ssh-session-colors "dark_gray green"
set -g @dracula-battery-colors "dark_gray light_purple"
set -g @dracula-cpu-usage-colors "dark_gray orange"
set -g @dracula-ram-usage-colors "dark_gray cyan"
set -g @dracula-weather-colors "dark_gray green"
set -g @dracula-spr-colors "dark_gray pink"
set -g @dracula-time-colors "dark_gray yellow"

set -g @dracula-border-contrast true

#set -g @dracula-show-flags true
#set -g @dracula-show-left-icon session

# go to beginning of a line like C-a a
bind a send-keys C-a

### Screen legacy

# toggle windows
bind-key C-a last-window

# C-a C-c
bind C-c new-window

bind | split-window -v -c '#{pane_current_path}'


### tmux startup windows
## Create a named session automatically (only if none exists)
#if-shell "tmux has-session -t main 2>/dev/null" "" "new-session -d -s main"
#
## Create window 2 and run htop
#new-window -t main:2 -n monitor 'htop'
#
## Select window 1 by default
#select-window -t main:1


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
